### ISSUE TITLE
timer connector - validation

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis-extensions#12]
Assuming the field was accepting milliseconds I have passed value `5555` that generated this error:

```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-02-02 15:19:19.338 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route -L4LxuReRL7JRsrvER8s: Route(-L4LxuReRL7JRsrvER8s)[[From[quartz2-1]] -> [Log[===$bo... because of CronExpression '5555' is invalid.
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1831) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:136) ~[camel-spring-2.20.1.jar!/:2.20.1]
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:174) ~[camel-spring-2.20.1.jar!/:2.20.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at io.syndesis.example.Application.main(Application.java:13) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:587) [project-0.1-SNAPSHOT.jar:na]
Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route -L4LxuReRL7JRsrvER8s: Route(-L4LxuReRL7JRsrvER8s)[[From[quartz2-1]] -> [Log[===$bo... because of CronExpression '5555' is invalid.
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:147) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3945) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3852) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3638) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3490) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:208) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3249) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3245) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3268) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3245) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3168) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:133) ~[camel-spring-2.20.1.jar!/:2.20.1]
	... 24 common frames omitted
Caused by: java.lang.RuntimeException: CronExpression '5555' is invalid.
	at org.quartz.CronScheduleBuilder.cronSchedule(CronScheduleBuilder.java:111) ~[quartz-2.3.0.jar!/:na]
	at org.apache.camel.component.quartz2.QuartzEndpoint.createTrigger(QuartzEndpoint.java:494) ~[camel-quartz2-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.quartz2.QuartzEndpoint.addJobInScheduler(QuartzEndpoint.java:384) ~[camel-quartz2-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.quartz2.QuartzEndpoint.doStart(QuartzEndpoint.java:340) ~[camel-quartz2-2.20.1.jar!/:2.20.1]
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75) ~[camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.component.proxy.ComponentProxyEndpoint.doStart(ComponentProxyEndpoint.java:149) ~[integration-component-proxy-1.2-SNAPSHOT.jar!/:1.2-SNAPSHOT]
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:157) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:145) ~[camel-core-2.20.1.jar!/:2.20.1]
	... 36 common frames omitted
Caused by: java.text.ParseException: Minute and Second values must be between 0 and 59
	at org.quartz.CronExpression.addToSet(CronExpression.java:973) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.CronExpression.checkNext(CronExpression.java:724) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.CronExpression.storeExpressionVals(CronExpression.java:693) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.CronExpression.buildExpression(CronExpression.java:487) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.CronExpression.<init>(CronExpression.java:276) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.CronScheduleBuilder.cronSchedule(CronScheduleBuilder.java:107) ~[quartz-2.3.0.jar!/:na]
	... 46 common frames omitted

```

@lburgazzoli do we have any help to specify any form of validation or protect us from errors like these?

**Comment by oscerd** [comment]
Here it expects a Cron expression.

**Comment by oscerd** [comment]
At least from the stacktrace
