### ISSUE TITLE
issue with irc extension

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis-extensions#21]
It turns out there is an issue with the IRC extension, showing itself only at deploy time:

```
paolo-2-9xn6g paolo Starting the Java application using /opt/run-java/run-java.sh ...
paolo-2-9xn6g paolo exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=9779:/tmp/src/prometheus-config.yml -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/project-0.1-SNAPSHOT.jar
paolo-2-deploy deployment --> Success
paolo-2-9xn6g paolo Exception in thread "main" java.lang.IllegalArgumentException: File must exist
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:67)
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:51)
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:83)
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.PropertiesLauncher.getArchive(PropertiesLauncher.java:494)
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:473)
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:443)
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
paolo-2-9xn6g paolo 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:58
```

If I restart the pod in debug I see that the env var `LOADER_HOME` is not set. I don't know if that's the real reason for the problem or just a side effect of running it with `oc debug`.

@lburgazzoli @oscerd @nicolaferraro  any idea?

**Comment by lburgazzoli** [comment]
LOADER_HOME is set [here](https://github.com/syndesisio/syndesis/blob/master/app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java#L213) so maybe `oc debug` does not inherit env vars ?
