### ISSUE TITLE
[Groovy] Error with some groovy scripts

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-extensions#3]
If you try to use the following groovy script:

```groovy
if ( ("$body".hashCode()%2)==1 ) {
  throw new RuntimeException("Odd hash codes.")
}
```

The integration fails to startup up.  With this error:
```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
--
  | 2018-01-19 22:32:13.778 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
  |  
  | org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route flow1 at: >>> To[class:io.syndesis.extension.GroovyExtension?method=runScript&bean.script=if ( ("$body".hashCode()%2)==1 ) {
  | throw new RuntimeException("Odd hash codes.")
  | }] <<< in route: Route(flow1)[[From[sql-start-connector-1?query=select+count%... because of Failed to resolve endpoint: class:io.syndesis.extension.GroovyExtension?method=runScript&bean.script=if ( ("$body".hashCode()%2)==1 ) {
  | throw new RuntimeException("Odd hash codes.")
  | } due to: Illegal character in opaque part at index 123: class:io.syndesis.extension.GroovyExtension?method=runScript&bean.script=if%20(%20(%22$body%22.hashCode()%252)==1%20)%20%7B
  | %20%20throw%20new%20RuntimeException(%22Odd%20hash%20codes.%22)
  | %7D
  | at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1831) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:136) ~[camel-spring-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:174) ~[camel-spring-2.20.1.jar!/:2.20.1]
  | at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
  | at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
  | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
  | at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
  | at io.syndesis.example.Application.main(Application.java:13) [classes!/:na]
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
  | at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
  | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [project-0.1-SNAPSHOT.jar:na]
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [project-0.1-SNAPSHOT.jar:na]
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [project-0.1-SNAPSHOT.jar:na]
  | at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:587) [project-0.1-SNAPSHOT.jar:na]
  | Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route flow1 at: >>> To[class:io.syndesis.extension.GroovyExtension?method=runScript&bean.script=if ( ("$body".hashCode()%2)==1 ) {
  | throw new RuntimeException("Odd hash codes.")
  | }] <<< in route: Route(flow1)[[From[sql-start-connector-1?query=select+count%... because of Failed to resolve endpoint: class:io.syndesis.extension.GroovyExtension?method=runScript&bean.script=if ( ("$body".hashCode()%2)==1 ) {
  | throw new RuntimeException("Odd hash codes.")
  | } due to: Illegal character in opaque part at index 123: class:io.syndesis.extension.GroovyExtension?method=runScript&bean.script=if%20(%20(%22$body%22.hashCode()%252)==1%20)%20%7B
  | %20%20throw%20new%20RuntimeException(%22Odd%20hash%20codes.%22)
  | %7D
  | at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:1298) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:204) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext.startRoute(DefaultCamelContext.java:1148) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:3727) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3441) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:208) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3249) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3245) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3268) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3245) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3168) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:133) ~[camel-spring-2.20.1.jar!/:2.20.1]
  | ... 24 common frames omitted
  | Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: class:io.syndesis.extension.GroovyExtension?method=runScript&bean.script=if ( ("$body".hashCode()%2)==1 ) {
  | throw new RuntimeException("Odd hash codes.")
  | } due to: Illegal character in opaque part at index 123: class:io.syndesis.extension.GroovyExtension?method=runScript&bean.script=if%20(%20(%22$body%22.hashCode()%252)==1%20)%20%7B
  | %20%20throw%20new%20RuntimeException(%22Odd%20hash%20codes.%22)
  | %7D
  | at org.apache.camel.impl.DefaultCamelContext.normalizeEndpointUri(DefaultCamelContext.java:836) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:690) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.util.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:80) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.model.RouteDefinition.resolveEndpoint(RouteDefinition.java:219) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:115) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:121) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.model.SendDefinition.resolveEndpoint(SendDefinition.java:62) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.model.SendDefinition.createProcessor(SendDefinition.java:56) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.model.ProcessorDefinition.makeProcessorImpl(ProcessorDefinition.java:549) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.model.ProcessorDefinition.makeProcessor(ProcessorDefinition.java:510) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.model.ProcessorDefinition.addRoutes(ProcessorDefinition.java:226) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:1295) ~[camel-core-2.20.1.jar!/:2.20.1]
  | ... 36 common frames omitted
  | Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 123: class:io.syndesis.extension.GroovyExtension?method=runScript&bean.script=if%20(%20(%22$body%22.hashCode()%252)==1%20)%20%7B
  | %20%20throw%20new%20RuntimeException(%22Odd%20hash%20codes.%22)
  | %7D
  | at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_151]
  | at java.net.URI$Parser.checkChars(URI.java:3021) ~[na:1.8.0_151]
  | at java.net.URI$Parser.parse(URI.java:3058) ~[na:1.8.0_151]
  | at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_151]
  | at org.apache.camel.util.URISupport.normalizeUri(URISupport.java:533) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.DefaultCamelContext.normalizeEndpointUri(DefaultCamelContext.java:834) ~[camel-core-2.20.1.jar!/:2.20.1]
  | ... 47 common frames omitted
  |  
  | 2018-01-19 22:32:13.782  INFO 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@341b80b2: startup date [Fri Jan 19


```

**Comment by lburgazzoli** [comment]
Yeah there is an issue with parameter sanitization (there is an pr) so you should write the script as a single line.

@paoloantinori wondering if beside options sanitization we should switch to extend SyndesisExtensionStep for this use case.

**Comment by paoloantinori** [comment]
Yeah, this is a known bug.
I have a PR open at the framework level since the real issue is that, in the way we have written the extension, it passes the whole script as a GET parameter, but `\n` characters are not allowed.

I have decided to push sanitization directly at Tech  Extension Framework level, so to protect other from this bug.

See PR here https://github.com/syndesisio/syndesis/pull/1148

We can workaround the issue entirely, if as @lburgazzoli  suggest we rewrite the extension extending a class instead than annotating a POJO.

Anyhow I still think that needs to be addressed at the framework side.

**Comment by paoloantinori** [comment]
fixed with https://github.com/syndesisio/syndesis/pull/1144
